name: Meta Check 2
on: pull_request

jobs:
  meta-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeNA/unity-meta-check@v3
        with:
          enable_pr_comment: true
          pr_comment_lang: en
          pr_comment_send_success: true
